# Generated by Django 3.2 on 2021-04-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Studio Name')),
                ('prefix', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('slug', models.SlugField(verbose_name='URL Param')),
            ],
        ),
    ]
