# Generated by Django 3.2 on 2021-04-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('sub_title', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=10)),
                ('slug', models.SlugField(verbose_name='Movie URL Param')),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='movies')),
                ('asin', models.CharField(max_length=12, verbose_name='Amazon Standard Identification Number')),
                ('directors', models.ManyToManyField(help_text='Directors of the movie', to='movies.Director')),
                ('genre', models.ManyToManyField(help_text='Genres of the movie', to='movies.Genre')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.studio')),
            ],
        ),
    ]
