# Generated by Django 3.2 on 2021-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Reviewer name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(default=None, max_length=512, null=True, verbose_name='Review text'),
        ),
    ]
